//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_KM
    {
        public string MA_KM { get; set; }
        public string MA_DSP { get; set; }
        public double PHANTRAMKM { get; set; }
    
        public virtual DONGSANPHAM DONGSANPHAM { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
    }
}
