//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUTRA
    {
        public int ID_PHIEUTRA { get; set; }
        public int ID_PHIEUDAT { get; set; }
        public int ID_SP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual CT_PHIEUDAT CT_PHIEUDAT { get; set; }
        public virtual PHIEUTRA PHIEUTRA { get; set; }
    }
}
