//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUDAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CT_PHIEUDAT()
        {
            this.CT_PHIEUTRA = new HashSet<CT_PHIEUTRA>();
        }
    
        public int ID_CTPD { get; set; }
        public int ID_PHIEUDAT { get; set; }
        public string MA_SP { get; set; }
        public int SOLUONG { get; set; }
        public int GIA { get; set; }
    
        public virtual PHIEUDAT PHIEUDAT { get; set; }
        public virtual SanPham SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUTRA> CT_PHIEUTRA { get; set; }
    }
}
