//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONGSANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONGSANPHAM()
        {
            this.CT_KM = new HashSet<CT_KM>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public string MA_DSP { get; set; }
        public string TEN { get; set; }
        public bool GIOITINH { get; set; }
        public string XUATXU { get; set; }
        public string MOTA { get; set; }
        public string HINHANH { get; set; }
        public string DOLUUHUONG { get; set; }
        public string MA_HANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_KM> CT_KM { get; set; }
        public virtual HANG HANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
