//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.PHIEUTRAs = new HashSet<PHIEUTRA>();
        }
    
        public string MA_HOADON { get; set; }
        public System.DateTime NGAYTAOHD { get; set; }
        public int TONGTIEN { get; set; }
        public int MASOTHUE { get; set; }
        public Nullable<int> ID_PHIEUDAT { get; set; }
        public string MA_NV { get; set; }
        public string MA_NVGH { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN_GH NHANVIEN_GH { get; set; }
        public virtual PHIEUDAT PHIEUDAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTRA> PHIEUTRAs { get; set; }
    }
}
