//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUYENMAI()
        {
            this.CT_KM = new HashSet<CT_KM>();
        }
    
        public string MA_KM { get; set; }
        public string TEN { get; set; }
        public System.DateTime NGAYBD { get; set; }
        public System.DateTime NGAYKT { get; set; }
        public string MOTA { get; set; }
        public string MA_NV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_KM> CT_KM { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
