//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PerfumeEntities : DbContext
    {
        public PerfumeEntities()
            : base("name=PerfumeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_DDH> CT_DDH { get; set; }
        public virtual DbSet<CT_KM> CT_KM { get; set; }
        public virtual DbSet<CT_PHIEUDAT> CT_PHIEUDAT { get; set; }
        public virtual DbSet<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        public virtual DbSet<CT_PHIEUTRA> CT_PHIEUTRA { get; set; }
        public virtual DbSet<CTVC> CTVCs { get; set; }
        public virtual DbSet<DONDATHANG> DONDATHANGs { get; set; }
        public virtual DbSet<DONGSANPHAM> DONGSANPHAMs { get; set; }
        public virtual DbSet<HANG> HANGs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHANVIEN_GH> NHANVIEN_GH { get; set; }
        public virtual DbSet<PHIEUDAT> PHIEUDATs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<PHIEUTRA> PHIEUTRAs { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THAYDOIGIA> THAYDOIGIAs { get; set; }
    
        public virtual ObjectResult<discount_line_perfume_Result> discount_line_perfume()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<discount_line_perfume_Result>("discount_line_perfume");
        }
    
        public virtual ObjectResult<get_all_discount_line_perfume_Result> get_all_discount_line_perfume()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_discount_line_perfume_Result>("get_all_discount_line_perfume");
        }
    
        public virtual ObjectResult<get_all_hang_Result> get_all_hang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_hang_Result>("get_all_hang");
        }
    
        public virtual ObjectResult<get_all_invoice_Result> get_all_invoice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_invoice_Result>("get_all_invoice");
        }
    
        public virtual ObjectResult<get_all_line_perfume_km_Result> get_all_line_perfume_km()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_line_perfume_km_Result>("get_all_line_perfume_km");
        }
    
        public virtual ObjectResult<get_all_linePerfume_by_DSP_Result> get_all_linePerfume_by_DSP(string mA_DSP)
        {
            var mA_DSPParameter = mA_DSP != null ?
                new ObjectParameter("MA_DSP", mA_DSP) :
                new ObjectParameter("MA_DSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_linePerfume_by_DSP_Result>("get_all_linePerfume_by_DSP", mA_DSPParameter);
        }
    
        public virtual ObjectResult<get_all_perfume_Result> get_all_perfume()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_perfume_Result>("get_all_perfume");
        }
    
        public virtual ObjectResult<get_all_perfume_by_hang_Result> get_all_perfume_by_hang(string mA_HANG)
        {
            var mA_HANGParameter = mA_HANG != null ?
                new ObjectParameter("MA_HANG", mA_HANG) :
                new ObjectParameter("MA_HANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_perfume_by_hang_Result>("get_all_perfume_by_hang", mA_HANGParameter);
        }
    
        public virtual ObjectResult<get_all_phieudat_Result> get_all_phieudat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_phieudat_Result>("get_all_phieudat");
        }
    
        public virtual ObjectResult<get_all_PN_Result> get_all_PN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_PN_Result>("get_all_PN");
        }
    
        public virtual ObjectResult<get_all_product_Result> get_all_product()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_product_Result>("get_all_product");
        }
    
        public virtual ObjectResult<get_all_shipper_Result> get_all_shipper()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_shipper_Result>("get_all_shipper");
        }
    
        public virtual ObjectResult<get_all_user_Result> get_all_user()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_user_Result>("get_all_user");
        }
    
        public virtual ObjectResult<get_CTDDH_by_MADDH_MASP_Result> get_CTDDH_by_MADDH_MASP(string maddh)
        {
            var maddhParameter = maddh != null ?
                new ObjectParameter("maddh", maddh) :
                new ObjectParameter("maddh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_CTDDH_by_MADDH_MASP_Result>("get_CTDDH_by_MADDH_MASP", maddhParameter);
        }
    
        public virtual ObjectResult<get_discount_line_perfume_Result> get_discount_line_perfume()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_discount_line_perfume_Result>("get_discount_line_perfume");
        }
    
        public virtual ObjectResult<get_DSP_KM_SP_Result> get_DSP_KM_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_DSP_KM_SP_Result>("get_DSP_KM_SP");
        }
    
        public virtual ObjectResult<get_employee_Result> get_employee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_employee_Result>("get_employee");
        }
    
        public virtual ObjectResult<get_line_product_for_display_Result> get_line_product_for_display()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_line_product_for_display_Result>("get_line_product_for_display");
        }
    
        public virtual ObjectResult<string> get_name_product_belong_hang(string mAHANG)
        {
            var mAHANGParameter = mAHANG != null ?
                new ObjectParameter("MAHANG", mAHANG) :
                new ObjectParameter("MAHANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("get_name_product_belong_hang", mAHANGParameter);
        }
    
        public virtual ObjectResult<get_order_by_status_Result> get_order_by_status(Nullable<int> tRANGTHAI)
        {
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_order_by_status_Result>("get_order_by_status", tRANGTHAIParameter);
        }
    
        public virtual ObjectResult<get_order_follow_user_by_status_Result> get_order_follow_user_by_status(string mAKH, Nullable<int> status)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_order_follow_user_by_status_Result>("get_order_follow_user_by_status", mAKHParameter, statusParameter);
        }
    
        public virtual ObjectResult<get_order_supply_Result> get_order_supply()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_order_supply_Result>("get_order_supply");
        }
    
        public virtual ObjectResult<get_order_supply_by_status_Result> get_order_supply_by_status(Nullable<int> status)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_order_supply_by_status_Result>("get_order_supply_by_status", statusParameter);
        }
    }
}
