//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN_GH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN_GH()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MA_NVGH { get; set; }
        public string HOTEN { get; set; }
        public string EMAIL { get; set; }
        public string SODIENTHOAI { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string MA_CTVC { get; set; }
    
        public virtual CTVC CTVC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
