//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUTRA()
        {
            this.CT_PHIEUTRA = new HashSet<CT_PHIEUTRA>();
        }
    
        public int ID_PHIEUTRA { get; set; }
        public System.DateTime NGAYTRA { get; set; }
        public string LYDO { get; set; }
        public Nullable<int> ID_HOADON { get; set; }
        public Nullable<int> ID_NV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUTRA> CT_PHIEUTRA { get; set; }
        public virtual HOADON HOADON { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
