//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAYDOIGIA
    {
        public string MA_SP { get; set; }
        public System.DateTime NGAY { get; set; }
        public int GIA { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
